### ISSUE TITLE
Format oracles in PGP

### ISSUE THREAD

**Issue by lambdafu** [hannob/pgpbugs#8]
F.  Maury,  J.-R.  Reinhard,  O.  Levillain,  and  H.  Gilbert,  “Formatoracles  on  openpgp,”  inTopics in Cryptology — CT-RSA 2015,K.  Nyberg,  Ed.Cham:  Springer  International  Publishing,  2015,pp. 220–236.

**Comment by hannob** [comment]
Free download: https://www.ssi.gouv.fr/uploads/2015/05/format-Oracles-on-OpenPGP.pdf
